version: 1.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: x86
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: SecuROMLoader.sln
  verbosity: minimal
